### ISSUE TITLE
NDPluginCodec fails to build on vxWorks 5.5

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADCore#359]
NDPluginCodec fails to build on vxWorks 5.5.  So far all other C++ code in ADCore builds on vxWorks 5.5, and although not essential I would like NDPluginCodec to build as well if it is not too difficult.

Here is the error:
```
../NDPluginCodec.cpp: In function `class NDArray * alloc(NDArray *, int = -1, unsigned int = 0, void * = 0)':
/usr/local/vw/tornado22-ppc/host/x86-linux/bin/../lib/gcc-lib/powerpc-wrs-vxworks/gcc-2.96/../../../../include/g++-3/stl_alloc.h:521: previous non-function declaration `typedef class __default_alloc_template<true,0> alloc'
../NDPluginCodec.cpp:73: conflicts with function declaration `class NDArray * alloc(NDArray *, int = -1, unsigned int = 0, void * = 0)'
../NDPluginCodec.cpp: In function `class NDArray * compressJPEG(NDArray *, int, NDCodecStatus_t *, char *)':
../NDPluginCodec.cpp:254: no matching function for call to `__default_alloc_template<true,0>::__default_alloc_template (NDArray *&, int, long unsigned int &, unsigned char *&)'
/usr/local/vw/tornado22-ppc/host/x86-linux/bin/../lib/gcc-lib/powerpc-wrs-vxworks/gcc-2.96/../../../../include/g++-3/stl_alloc.h:377: candidates are: __default_alloc_template<true,0>::__default_alloc_template(const __default_alloc_template<true,0> &)
/usr/local/vw/tornado22-ppc/host/x86-linux/bin/../lib/gcc-lib/powerpc-wrs-vxworks/gcc-2.96/../../../../include/g++-3/stl_alloc.h:377:                 __default_alloc_template<true,0>::__default_alloc_template()
../NDPluginCodec.cpp: In function `class NDArray * decompressJPEG(NDArray *, NDCodecStatus_t *, char *)':
../NDPluginCodec.cpp:289: no matching function for call to `__default_alloc_template<true,0>::__default_alloc_template (NDArray *&, NDDataType_t)'
/usr/local/vw/tornado22-ppc/host/x86-linux/bin/../lib/gcc-lib/powerpc-wrs-vxworks/gcc-2.96/../../../../include/g++-3/stl_alloc.h:377: candidates are: __default_alloc_template<true,0>::__default_alloc_template(const __default_alloc_template<true,0> &)
/usr/local/vw/tornado22-ppc/host/x86-linux/bin/../lib/gcc-lib/powerpc-wrs-vxworks/gcc-2.96/../../../../include/g++-3/stl_alloc.h:377:                 __default_alloc_template<true,0>::__default_alloc_template()
/usr/local/vw/tornado22-ppc/host/x86-linux/bin/../lib/gcc-lib/powerpc-wrs-vxworks/gcc-2.96/../../../../include/g++-3/stl_multiset.h: At top level:
../NDPluginCodec.cpp:73: warning: `class NDArray * alloc(NDArray *, int = -1, unsigned int = 0, void * = 0)' defined but not used
/Jenkins/jenkins/jobs/epics-base-3.14/workspace/configure/RULES_BUILD:223: recipe for target 'NDPluginCodec.o' failed
make[4]: *** [NDPluginCodec.o] Error 1
```
