### PR TITLE
Eliminate shareLib.h

### PR DESCRIPTION
**Pull request by MarkRivers**
This PR converts ADCore from using the traditional shareLib.h with epicsShareFunc, epicsShareExtern, epicsShareClass, etc. to using the mechanism now used in base. 

- Added ADCoreAPI.h, NDPluginAPI.h, and ntndArrayConverterAPI.h.  
- Modified Makefiles.
- Modified all code to use the new mechanism.

### CODE REVIEW

**Comment by MarkRivers** [comment]
This addresses issue #455.

**Comment by MarkRivers** [comment]
@xiaoqiangwang and @anjohnson I would appreciate your comments.  I can't formally assign you as reviewers or assignees.

**Comment by xiaoqiangwang** [comment]
Sorry I did not see this earlier. Is this suppose to only work with asyn with ASYN_API changes?
Using asyn 3.38, there is an error in symbols declared by asynDriver.h.
```
   Creating library ADBase.lib and object ADBase.exp
NDArrayPool.obj : error LNK2001: unresolved external symbol _pasynTrace
ADBase.dll : fatal error LNK1120: 1 unresolved externals
make[3]: *** [/home/scratch/base-7.0.4/configure/RULES_BUILD:298: ADBase.dll] Error 96
make[3]: Leaving directory '/home/scratch/synApps/support/areaDetector/ADCore/ADApp/ADSrc/O.win32-x86'
make[2]: *** [/home/scratch/base-7.0.4/configure/RULES_ARCHS:58: install.win32-x86] Error 2
make[2]: Leaving directory '/home/scratch/synApps/support/areaDetector/ADCore/ADApp/ADSrc'
make[1]: *** [/home/scratch/base-7.0.4/configure/RULES_DIRS:85: ADSrc.install] Error 2
make[1]: Leaving directory '/home/scratch/synApps/support/areaDetector/ADCore/ADApp'
make: *** [/home/scratch/base-7.0.4/configure/RULES_DIRS:85: ADApp.install] Error 2
```

**Comment by MarkRivers** [comment]
Peter Heesterman reported a similar issue:
> OK, so I updated to asyn R4-40-1, as the most recent release.
This removed the 'already defined' errors, but left the
NDArrayPool.obj : error LNK2001: unresolved external symbol _pasynTrace

> So I then, as you say, cloned the master branch.
Which did remove the above problem.

> I see that a similar approach - using BUILDING_asyn_API - has been followed within the asyn module, but this is not yet included in a release.

> Now the error I get is:
NDPluginAttribute.obj : error LNK2005: "public: __thiscall epicsThreadRunable::epicsThreadRunable(class epicsThreadRunable const &)" (??0epicsThreadRunable@@QAE@ABV0@@Z) already defined in ADBase.lib(ADBase.dll)
NDPluginAttribute.obj : error LNK2005: "public: __thiscall epicsThreadRunable::epicsThreadRunable(void)" (??0epicsThreadRunable@@QAE@XZ) already defined in ADBase.lib(ADBase.dll)
NDPluginAttribute.obj : error LNK2005: "public: class epicsThreadRunable & __thiscall epicsThreadRunable::operator=(class epicsThreadRunable const &)" (??4epicsThreadRunable@@QAEAAV0@ABV0@@Z) already defined in ADBase.lib(ADBase.dll)
NDPlugin.dll : fatal error LNK1169: one or more multiply defined symbols found

> I guess this only works if I also update to the most recent EPICS base?

**Comment by MarkRivers** [comment]
This branch does build OK with base 7.0.4.1 and the master branch of asyn.  

However, I would like to make it also build with older versions of asyn and older versions of base.  So I will push some changes that should fix the issues that you have found, and then I will ask you to please test again.

**Comment by MarkRivers** [comment]
I have pushed changes to NDArrayPool.cpp and NDPluginAttribute.cpp.  Please see if this fixes the errors on older versions of asyn and base.

**Comment by xiaoqiangwang** [comment]
Some other source files seem to need the same change.
```
   Creating library NDPlugin.lib and object NDPlugin.exp                                                                                    
NDPluginCircularBuff.obj : error LNK2001: unresolved external symbol _pasynTrace                                                            
NDPluginGather.obj : error LNK2001: unresolved external symbol _pasynManager                                                                
NDPlugin.dll : fatal error LNK1120: 2 unresolved externals                                                                                  
make[3]: *** [/home/scratch/base-7.0.4/configure/RULES_BUILD:298: NDPlugin.dll] Error 96                                                    
make[3]: Leaving directory '/home/scratch/synApps/support/areaDetector/ADCore/ADApp/pluginSrc/O.win32-x86'                                  
make[2]: *** [/home/scratch/base-7.0.4/configure/RULES_ARCHS:58: install.win32-x86] Error 2                                                 
make[2]: Leaving directory '/home/scratch/synApps/support/areaDetector/ADCore/ADApp/pluginSrc'                                              
make[1]: *** [/home/scratch/base-7.0.4/configure/RULES_DIRS:85: pluginSrc.install] Error 2                                                  
make[1]: Leaving directory '/home/scratch/synApps/support/areaDetector/ADCore/ADApp'                                                        
make: *** [/home/scratch/base-7.0.4/configure/RULES_DIRS:85: ADApp.install] Error 2           
```

**Comment by MarkRivers** [comment]
Thank @xiaoqiangwang. I have set up a new test tree for myself with asyn R4-38 and base 3.15.5. So I should be able to find and fix these myself. I’ll let you know when I am ready for you to test again.

**Comment by MarkRivers** [comment]
I just added some more #include statements, and the Without_shareLib branch now builds with asyn R4-38 and base 3.15.5.  I tested with VS2015 both static and dynamic.

@xiaoqiangwang and Peter H. please test that it works for you.

**Comment by MarkRivers** [comment]
When I did dumpbin /exports I found the ADBase.dll was exporting an asynPortDriver function.  I fixed that. NDPlugin.dll is also exporting some asynPortDriver and epicsTime functions as viewed with dumpbin /exports.  However it is not causing any link errors for me so I have not tried to fix it.

**Comment by MarkRivers** [comment]
I fixed the problem with NDPlugin.dll exporting asynPortDriver and epicsTime functions. 

The windows dynamic build now appears to be clean with asyn R4-38 and base 3.15.5.

**Comment by xiaoqiangwang** [comment]
My build with EPICS base 7.0.4.0 and asyn 4.38 is good. The exported symbols list is clean.

**Comment by MarkRivers** [comment]
> My build with EPICS base 7.0.4.0 and asyn 4.38 is good. The exported symbols list is clean.

OK, good.

**Comment by MarkRivers** [comment]
Peter H. also had no problems with the latest Without_shareLib branch so I am merging it.
